/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TeamAssigment1;

import java.util.Scanner;

public class TeamAssigment1 {

    public static void main(String[] args) {
       
        System.out.println("======== Selamat Malam! =======");
        System.out.println(" ");
        Scanner jmlOrg = new Scanner(System.in);
        System.out.print("Mau Pesan Untuk Berapa Orang : ");
        String jumlahOrang = jmlOrg.nextLine();
        Scanner objAtasnama = new Scanner(System.in);
        System.out.print("Pesanan Atas Nama : ");
        String atasNama = objAtasnama.nextLine();
        
        double hargaNasgor = 9999.99;
        double hargaAyamBakar = 12345.67;
        double hargaSteak = 21108.40;
        double hargaKwetiaw = 13579.13;
        double hargaKambing = 98765.43;
        
        System.out.println("Menu Spesial Hari Ini");
        System.out.println("=====================");
        System.out.println(" ");
        System.out.println("1. Nasi Goreng Spesial                   Rp.9999.99");
        System.out.println("2. Ayam Bakar Spesial                   Rp.12345.67");
        System.out.println("3. Steak Sirloin Spesial                Rp.21108.40");
        System.out.println("4. Kwetiaw Siram Spesial                Rp.13579.13");
        System.out.println("5. Kambing Guling Spesial               Rp.98765.43");
        System.out.println(" ");
        System.out.println("Pesanan anda (Batas pesanan 10 pre-order)");
        
        Scanner obJumlahNasgor = new Scanner(System.in);
        System.out.print("Nasi Goreng Spesial : ");
        int jumlahNasgor = obJumlahNasgor.nextInt();
        if (jumlahNasgor > 10) {
            System.out.println("Pesanan Anda Melebihi Batas Porsi, Silahkan Pesan Ulang");
            jumlahNasgor = 0;
            System.out.print("Nasi Goreng Spesial :");
            jumlahNasgor = obJumlahNasgor.nextInt();
        }
      
        Scanner obJumlahAyamBakar = new Scanner(System.in);
        System.out.print("Ayam Bakar Spesial : ");
        int jumlahAyamBakar = obJumlahAyamBakar.nextInt();
        if (jumlahAyamBakar > 10) {
            System.out.println("Pesanan Anda Melebihi Batas Porsi, Silahkan Pesan Ulang");
            jumlahAyamBakar = 0;
            System.out.print("Ayam Bakar Spesial :");
            jumlahAyamBakar = obJumlahAyamBakar.nextInt();
        }
   
        Scanner objJumlahSteak = new Scanner(System.in);
        System.out.print("Steak Sirloin Spesial : ");
        int jumlahSteak = objJumlahSteak.nextInt();
        if (jumlahSteak > 10) {
            System.out.println("Pesanan Anda Melebihi Batas Porsi, Silahkan Pesan Ulang");
            jumlahSteak = 0;
            System.out.print("Steak Sirloin Spesial :");
            jumlahSteak = objJumlahSteak.nextInt();
        }
            
        Scanner obJumlahKwetiaw = new Scanner(System.in);
        System.out.print("Kwetiaw Siram Spesial : ");
        int jumlahKwetiaw = obJumlahKwetiaw.nextInt();
        if (jumlahKwetiaw > 10) {
            System.out.println("Pesanan Anda Melebihi Batas Porsi, Silahkan Pesan Ulang");          
            jumlahKwetiaw = 0;
            System.out.print("Kwetiaw Kuah Siram Spesial :");
            jumlahKwetiaw = obJumlahKwetiaw.nextInt();
        }
        Scanner obJumlahKambingGuling = new Scanner(System.in);
        System.out.print("Kambing Guling Spesial : ");
        int jumlahKambingGulingSpesial = obJumlahKambingGuling.nextInt();
        if (jumlahKambingGulingSpesial > 10) {
            System.out.println("Pesanan Anda Melebihi Batas Porsi, Silahkan Pesan Ulang");           
            jumlahKambingGulingSpesial = 0;
            System.out.print("Kambing Guling Spesial :");
            jumlahKambingGulingSpesial =obJumlahKambingGuling.nextInt();
        }
        
        int jumlahPesanan = jumlahNasgor+jumlahAyamBakar+jumlahSteak+jumlahKwetiaw+jumlahKambingGulingSpesial;
        
        System.out.println(" ");
        System.out.println("                                         Selamat menikmati makanan anda !                                      ");
        System.out.println(" ");
        double totalNasgor = jumlahNasgor * hargaNasgor;
        double totalAyam = jumlahAyamBakar * hargaAyamBakar;
        double totalSteak = jumlahSteak * hargaSteak;
        double totalKwetiaw = jumlahKwetiaw * hargaKwetiaw;
        double totalKambing = jumlahKambingGulingSpesial * hargaKambing;
        double totalPembelian = totalNasgor+totalAyam+totalSteak+totalKwetiaw+totalKambing;
        double totalDiskon = totalPembelian * 0.1;
        double hargaAkhir = totalPembelian - totalDiskon;
        double hargaPerOrang = hargaAkhir / jumlahPesanan;
                
        System.out.println("Rincian Pesanan :");
        System.out.println(" ");
        System.out.println("Pesanan Atas Nama : " + atasNama);
        System.out.println(" ");
        System.out.println("Nasi Goreng Spesial    " + jumlahNasgor + "Porsi x " + hargaNasgor + "= Rp." + totalNasgor);
        System.out.println("Ayama Bakar Spesial    " + jumlahAyamBakar + "Porsi x " + hargaAyamBakar + "= Rp." + totalAyam);
        System.out.println("Steak Sirloin Spesial  " + jumlahSteak + "Porsi x " + hargaSteak + "= Rp." + totalSteak);
        System.out.println("Kwetiaw Siram Spesial  " + jumlahKwetiaw + "Porsi x " + hargaKwetiaw + "= Rp." + totalKwetiaw);
        System.out.println("Kambing Guling Spesial " + jumlahKambingGulingSpesial + "Porsi x " + hargaKambing + "= Rp." + totalKambing);
        System.out.println("=================================================================================================================");
        System.out.println("Total Pembelian                                                                      = Rp." + totalPembelian);
        System.out.println(" ");
        System.out.println("Diskon 10% (Masa Promosi)                                                            = Rp." + totalDiskon);
        System.out.println("=================================================================================================================");
        System.out.println("Total Pembelian Dengan Diskon 10%                                                    = Rp." + hargaAkhir);
        System.out.println("Pembelian Per Orang (Untuk " + jumlahOrang + " Orang)                                                 = Rp." + hargaPerOrang);
        System.out.println(" ");
        System.out.println("                                        Terima Kasih Atas Kunjungan Anda !                                       ");
        System.out.println(" ");
        System.out.println("Press \"ENTER\" to exit...");
        Scanner scanner = new Scanner(System.in);
        scanner.nextLine();
        System.exit(0);
 
    }
}
