/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TeamAssigment1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TeamAssigment1Test {
    @Test void appHasAGreeting() {
       
    }
}
